version: '3'
services:
  app: 
    build: .
    container_name: graphci
    environment:
      - DATABASE_URL=mysql://root:root@localhost:5432/graphci
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=graphci   
      - MYSQL_USER=root         
      - MYSQL_PASSWORD=root
    ports:  
      - "5432:5432"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: